version: "3"
x-restart-policy: &restart_policy
  restart: always
x-healthcheck-defaults: &healthcheck_defaults
  interval: 30s
  timeout: 5s
  retries: 5
  start_period: 10s
services:
  redis:
    <<: *restart_policy
    image: redis:${REDIS_VERSION}
    container_name: ${CONTAINER_PREFIX}redis
    environment:
      TZ: "$TZ"
    volumes:
      - ${REDIS_ACL_FILE}:/etc/redis/users.acl:ro,cached
      - ${REDIS_CONF_FILE}:/etc/redis/redis.conf:ro,cached
      - ${DATA_DIR}/redis:/data/:rw,delegated
    ports:
      - "${REDIS_HOST_PORT}:6379"
    entrypoint: ["redis-server", "/etc/redis/redis.conf"]
    healthcheck:
      <<: *healthcheck_defaults
      test: ["CMD", "redis-cli", "ping"]
    networks:
      - default

  mongodb:
    <<: *restart_policy
    image: mongo:${MONGODB_VERSION}
    container_name: ${CONTAINER_PREFIX}mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGODB_INITDB_ROOT_USERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGODB_INITDB_ROOT_PASSWORD}"
      TZ: "$TZ"
    volumes:
      - ${DATA_DIR}/mongo:/data/db:rw,delegated
      - ${DATA_DIR}/mongo_key:/mongo:rw,delegated
    ports:
      - "${MONGODB_HOST_PORT}:27017"
    healthcheck:
      <<: *healthcheck_defaults
      test: echo 'db.runCommand("ping").ok' | mongo 127.0.0.1:27017/test --quiet
    networks:
      - default
    command:
      --auth

  mysql5:
    <<: *restart_policy
    image: mysql:${MYSQL5_VERSION}
    container_name: ${CONTAINER_PREFIX}mysql5
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL5_ROOT_PASSWORD}"
      TZ: "$TZ"
    volumes:
      - ${MYSQL5_CONF_FILE}:/etc/mysql/conf.d/mysql.cnf:ro,cached
      - ${DATA_DIR}/mysql5:/var/lib/mysql/:rw,delegated
    ports:
      - "${MYSQL5_HOST_PORT}:3306"
    healthcheck:
      <<: *healthcheck_defaults
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
    networks:
      - default

  mysql8:
    <<: *restart_policy
    image: mysql:${MYSQL8_VERSION}
    container_name: ${CONTAINER_PREFIX}mysql8
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL8_ROOT_PASSWORD}"
      TZ: "$TZ"
    volumes:
      - ${MYSQL8_CONF_FILE}:/etc/mysql/conf.d/mysql.cnf:ro,cached
      - ${DATA_DIR}/mysql8:/var/lib/mysql/:rw,delegated
    ports:
      - "${MYSQL8_HOST_PORT}:3306"
    healthcheck:
      <<: *healthcheck_defaults
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
    networks:
      - default

  memcached:
    <<: *restart_policy
    image: memcached:${MEMCACHED_VERSION}
    container_name: ${CONTAINER_PREFIX}memcached
    environment:
      MEMCACHED_CACHE_SIZE: "${MEMCACHED_CACHE_SIZE}"
      MEMCACHED_MAX_CONNECTIONS: "${MEMCACHED_MAX_CONNECTIONS}"
      # MEMCACHED_THREADS: "${MEMCACHED_THREADS}"
      # MEMCACHED_USERNAME: "${MEMCACHED_USERNAME}"
      # MEMCACHED_PASSWORD: "${MEMCACHED_PASSWORD}"
    ports:
      - "${MEMCACHED_HOST_PORT}:11211"
    healthcheck:
      <<: *healthcheck_defaults
      test: echo stats | nc 127.0.0.1 11211
    networks:
      - default

networks:
  default:
